version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:12-stretch

    working_directory: ~/repo

jobs:
  build:
    executor: node-executor

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # Fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Resolve Dependencies
          command: yarn install

      - run:
          name: Build
          command: yarn build

      - run:
          name: Create a workspace
          command: mkdir -p /tmp/workspace

      - run:
          name: Copy to workspace
          command: cp -r ./* /tmp/workspace/

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - '*'
